---
- hosts: bastion
  gather_facts: true
  vars:
    app_name: devops-ais
  tasks:
  - name: copy the helm charts to the bastion
    synchronize:
     src: ../charts/
     dest: /tmp/ais_deploy
     recursive: True
  - name: copy the script to bastion
    copy:
       src: deploy_ais.sh
       dest: /tmp/ais_deploy
       mode: 0755
  - name: copy the kubeconfig to the bastion
    copy:
       src: admin.conf
       dest: /tmp/ais_deploy/kube.conf
       mode: 0755
  - name: copy the docker image_tag.txt to the bastion
    copy:
       src: image_tag.txt
       dest: /tmp/ais_deploy/image_tag.txt
       mode: 0644
  - name: add ais_node labels
    command: kubectl label nodes "{{ item }}" ais-node=yes --overwrite
    with_inventory_hostnames:
       -  proxy-node
       -  target-node
       -  neproxy-node
    environment:
        KUBECONFIG='/tmp/ais_deploy/kube.conf'
  - name: add node proxy labels
    command: kubectl label nodes "{{ item }}" ais-proxy-type=electable --overwrite
    with_inventory_hostnames:
       -  proxy-node
    environment:
        KUBECONFIG='/tmp/ais_deploy/kube.conf'
  - name: add target node labels
    command: kubectl label nodes "{{ item }}" ais-target-node=yes --overwrite
    with_inventory_hostnames: 
        - target-node
    environment:
        KUBECONFIG=/tmp/ais_deploy/kube.com
  - name: add NE proxy node labels
    command: kubectl label nodes "{{ item }}" ais-proxy-type=nonelectable --overwrite
    with_inventory_hostnames:
        - neproxy-node
    environment:
        KUBECONFIG=/tmp/ais_deploy/kube.com
  - name: run the deploy script
    command: chdir=/tmp/ais_deploy  ./deploy_ais.sh kube.conf {{ app_name }}
