image: golang:1.13

stages:
  - build
  - test-short

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

before_script:
  - apt-get clean && apt-get update
  - apt-get --no-install-recommends -y install curl git sysstat attr build-essential lsof fuse
  - apt-get -y clean all
  - mkdir -p /go/src/github.com/NVIDIA /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/github.com/NVIDIA/aistore
  - ln -s /go/src/github.com/NVIDIA/aistore /go/src/_/builds/NVIDIA
  - cd /go/src/github.com/NVIDIA/aistore

build:linux:
  stage: build
  script:
    - CLDPROVIDER="aws" make node
    - CLDPROVIDER="gcp" make node
    - CLDPROVIDER="ais" make node
    - CLDPROVIDER="" make node
    - make authn
    - make aisfs
    - make cli
    - make aisloader

build:darwin:
  stage: build
  script:
    - GOOS="darwin" CLDPROVIDER="aws" make node
    - GOOS="darwin" CLDPROVIDER="gcp" make node
    - GOOS="darwin" CLDPROVIDER="ais" make node
    - GOOS="darwin" CLDPROVIDER="" make node
    - GOOS="darwin" make authn
    - GOOS="darwin" make aisfs
    - GOOS="darwin" make cli
    - GOOS="darwin" make aisloader

lint:linux:
  stage: build
  script:
    - make lint
    - make fmt-check
    - make spell-check

lint:darwin:
  stage: build
  script:
    - GOOS="darwin" make lint
    - GOOS="darwin" make fmt-check
    - GOOS="darwin" make spell-check

test:short:
  stage: test-short
  script:
    - make cli aisfs
    - make deploy <<< $'5\n5\n3\n0'
    - BUCKET="test" make test-short
