image: golang:1.13

stages:
  - build
  - lint
  - test-short

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

before_script:
  - apt-get clean && apt-get update
  - apt-get --no-install-recommends -y install curl git sysstat attr build-essential lsof
  - apt-get -y clean all
  - mkdir -p /go/src/github.com/NVIDIA /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/github.com/NVIDIA/aistore
  - ln -s /go/src/github.com/NVIDIA/aistore /go/src/_/builds/NVIDIA
  - cd /go/src/github.com/NVIDIA/aistore/ais

build:
  stage: build
  script:
    - go build -tags="aws" setup/aisnode.go
    - go build -tags="gcp" setup/aisnode.go
    - go build -tags="" setup/aisnode.go

lint:
  stage: build
  script:
    - make lint
    - make fmt-check
    - make spell-check

test-short:
  stage: test-short
  script:
    - printf '5\n5\n2\n0' | make deploy
    - BUCKET=test make test-short
