image: golang:1.13

.test_long_template: &test_long_def
  stage: test-long
  only:
    - schedules
  after_script:
    - mkdir $CI_PROJECT_DIR/logs
    - find /tmp/ais -type f -name "*log*" -exec cp {} $CI_PROJECT_DIR/logs/ \;
  artifacts:
    when: on_failure
    paths: [logs/]
    expire_in: 2 days

stages:
  - build
  - test-short
  - test-long

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

before_script:
  - apt-get clean && apt-get update
  - apt-get --no-install-recommends -y install curl git sysstat attr build-essential lsof fuse
  - apt-get -y clean all
  - mkdir -p /go/src/github.com/NVIDIA /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/github.com/NVIDIA/aistore
  - ln -s /go/src/github.com/NVIDIA/aistore /go/src/_/builds/NVIDIA
  - cd /go/src/github.com/NVIDIA/aistore

build:linux:
  stage: build
  script:
    - CLDPROVIDER="aws" make node
    - CLDPROVIDER="gcp" make node
    - CLDPROVIDER="ais" make node
    - CLDPROVIDER="azure" make node
    - CLDPROVIDER="" make node
    - make authn
    - make aisfs
    - make cli
    - make aisloader

lint:linux:
  stage: build
  script:
    - apt-get install -y python3-pip
    - pip3 install setuptools yapf pylint
    - make lint
    - make fmt-check
    - make spell-check

test:short:
  stage: test-short
  script:
    - make cli aisfs
    - make deploy <<< $'5\n5\n3\n0'
    - BUCKET="test" make test-short

test:long:
  <<: *test_long_def
  script:
    - make deploy <<< $'6\n5\n3\n0'
    - BUCKET="test" make test-long

test:cloud:
  <<: *test_long_def
  variables:
    AWS_REGION: us-west-2
  script:
    - make deploy <<< $'6\n5\n3\n1'
    - BUCKET="ci-aistore" make test-long

test:soak:
  stage: test-long
  only:
    - schedules
  script:
    - make deploy <<< $'5\n5\n3\n0'
    - FLAGS="--short --rec-cycles=1" make test-soak
