[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/pbnjay/memory"

[[constraint]]
  name = "github.com/cloudfoundry/gosigar"
  version = "1.1.0"
