# Default values for ais_test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/nvidia/ais_test
  tag: 21
  pullPolicy: IfNotPresent
  dockerRepoToken: ""

test_params: 
# Specify an endpoint for reaching the proxy service.
  proxy_endpoint: "" 
  proxy_port: "8080"
  num_targets: "5"
  test_bucket: "ais-test-bucket"
  test_duration: "180s"

nodeSelector: {}
ingress: {}
tolerations: []

affinity: {}
