#
# Pre-install hook for Helm, to cleanup smap.json from any past ais release.
#
# We start a DaemonSet with affinity to match any one of our label selectors
# for proxy, non-electable proxy & target nodes. Since Helm regards a hook of
# resource kind DaemonSet as non-blocking (it is considered ready as soon as
# it is loaded) we follow up with an additional pre-install hook that blocks
# for a bit to allow this one to run to completion.
#
# When the command exits, k8s will relaunch the container (this being a DaemonSet)
# and there's nothing we seem to be able to do about that. But Helm is satisfied
# once all pods have completed one scheduling trip, and then proceeds to delete
# the resource.
#
# XXX Actually, the interaction between Helm and a DaemonSet preinstall hook is unclear. Helm
# does not block on this type, and it *seemed* to consider the hook complete when each
# pod container has been started on all nodes matching the node selector criteria.
# But some experience shows that if a node is delayed in scheduling and executing
# one of the dameonset containers (as was the case on one node with a runaway kworker process)
# then Helm is still quite happy to consider the preinstall hook complete.
#
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "ais.fullname" . }}-pre-install-hook
  labels:
    app: {{ template "ais.name" . }}
    chart: {{ template "ais.chart" . }}
    component: "pre-install-hook"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app: {{ template "ais.name" . }}
        component: "pre-install-hook"
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: pre-install-job
        image: "alpine:3.3"
        command: ["/bin/sh"]
        args: [ "-c", "rm -f /etc/ais/*/smap.json /etc/ais/*/helminstall.timestamp; touch /etc/ais/rmhookdone.timestamp" ]
        volumeMounts:
           - name: etc-mount
             mountPath: "{{ .Values.ais_config_common.confdir }}"
      volumes:
        - name: etc-mount
          hostPath:
            path: {{ .Values.pre_install_hook.etcMountPath.hostPath }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.proxy.nodeSelector.key }}
                operator: In
                values:
                  - {{ .Values.proxy.nodeSelector.value | quote }}
                  - {{ .Values.ne_proxy.nodeSelector.value | quote }}
            - matchExpressions:
              - key: {{ .Values.target.nodeSelector.key }}
                operator: In
                values:
                  - {{ .Values.target.nodeSelector.value | quote }}

