version: '3'
services:
  aisproxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CLDPROVIDER=${CLDPROVIDER}
    ports:
      - "8080:8080"
    environment:
      - ROLE-proxy
      - AIS_PRIMARYPROXY=${AIS_PRIMARYPROXY}
    env_file:
      - aws.env
  aistarget:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ROLE=target
    env_file:
      - aws.env
