replicaCount: 1

image:
  repository: quay.io/nvidia/aisloader
  tag: 1
  pullPolicy: IfNotPresent
  pullSecret: requireoverride

#
# The release name for AIS, ie the name used in 'helm install --name=foo .'' for the AIS install.
# This is used in finding the proxy clusterIP, and for the graphite host.
#
ais_release: "stress"

#
# Arguments with which to run aisloader.
#
# 'ip' default is not listed below, it defaults to "{{ .Values.ais_release}}-ais-proxy }}"
#
# In each case we first look for an argument indexed by node name, and fall back to the
# default.
#
#
aisloaderArg:
  # If the 'bucket' name includes %s it will be substituted with the node name
  bucket:
    default: "stressbkt_%s"
    specific: []
  duration:
    default: "30m"
    # Example of how to specify per-host values
    # specific:
    #  - node: "cpu01"
    #    value: "29m"
  pctput:
    default: "0"
    specific: []
  cleanup:
    default: "false"
    specific: []
  readertype:
    default: "sg"
    specific: []
  numworkers:
    default: "50"
    specific: []
  ip:
    # no default - see above
    specific: []
  port:
    default: "51080"
    specific: []
  minsize:
    default: "8M"
    specific: []
  maxsize:
    default: "8M" 
    specific: []
  seed:
    # can be 'fromhostip' (last component of host IP), 'random' (shell $RANDOM) or '0' (time in ns)
    default: "fromhostip"
    specific: []
  statsinterval:
    default: "60"
    specific: []
  uniquegets:
    default: "true"
    specific: []
  putshards:
    default: "0"
    specific: []
  maxputs:
    default: "0"
    specific: []
  no_detailed_stats:
    default: "true"
    specific: []
  readlen:
    default: "0"
    specific: []
  readoff:
    default: "0"
    specific: []



resources: {}

nodeSelector:
  aisloader: "yes"

tolerations: []

affinity: {}
