#
# Taint cpu nodes to keep others off our lawn. The ais DaemonSet pods will tolerate
# this taint, as will the Graphite and Grafana subcharts of ais.
#
# We specify PreferNoSchedule for some flexibility. For example, some DL jobs will
# have components that require CPU node scheduling (and we may not have dedicated
# CPU nodes for that purpose). Similarly, in an AIS-only k8s cluster it would be
# tedious to have to add tolerations to anything we want to run.
#
---
- hosts: '{{ playhosts | default("cpu-worker-node") }}'
  vars_files:
    - "vars.yml"

  gather_facts: False
  roles:
    - { role: ais_taint_nodes }