- name: Run aisloader "{{ bench_type }}" on bucket {{ bucket }}
  hosts: aisloader_hosts
  gather_facts: no
  vars_files:
    - "vars/bench.yaml"

  tasks:
  - name: Start aisloader GET
    ansible.builtin.script: scripts/aisloader_script.sh --bench_type={{ bench_type }} --s3_endpoint={{ s3_endpoint }} --bucket={{ bucket }} --duration={{ duration }} --grafana_host={{ hostvars[grafana_host].ansible_host }} --workers={{ get_workers.value }}
    when: bench_type == "get"

  - name: Start aisloader PUT
    ansible.builtin.script: scripts/aisloader_script.sh --bench_type={{ bench_type }} --s3_endpoint={{ s3_endpoint }} --bucket={{ bucket }} --each_size={{ bench_size }} --total_size={{ total_size }} --grafana_host={{ hostvars[grafana_host].ansible_host }} --workers={{ put_workers.value }}
    when: bench_type == "put"

  - name: Find the output files
    find:
      paths: /tmp/aisloader/
      patterns: "{{ bucket }}-direct-{{ bench_type }}*"
      use_regex: False
    register: outfiles

  - name: Fetch the output files from remote
    fetch:
      src: "{{ item.path }}"
      dest: ../output/direct/{{ bench_type }}/{{ bucket }}/
      flat: yes
    with_items: "{{ outfiles.files }}"