apiVersion: v1
kind: Pod
metadata:
  name: aisproxy-${ID}
  labels:
    type: aisproxy
spec:
  hostNetwork: true
  containers:
  - name: aisproxy
    image: ${DOCKER_HOST_IP}:5000/ais:v1
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /v1/health
        port: ${PORT}
      initialDelaySeconds: 20
      periodSeconds: 10
    env:
     - name: AIS_NODE_ROLE
       value: "proxy"
     - name: AIS_IS_PRIMARY
       value: "${AIS_IS_PRIMARY}"
     - name: AIS_DAEMON_ID
       value: "ais-proxy-${ID}"
    volumeMounts:
     - name: aws-credentials
       mountPath: /root/.aws/
     - name: ais-log
       mountPath: /tmp/
    ports:
      - containerPort: ${PORT}
    # TODO: fix the workaround of AIS_FS_PATHS
    command: ["bash","-c"]
    args:
      - export PORT=${PORT} &&
        export AIS_FS_PATHS="\"\"${AIS_FS_PATHS}\"\"" &&
        export TEST_FSPATH_COUNT=${TEST_FSPATH_COUNT} &&
        export IPV4LIST=${IPV4LIST} &&
        export AIS_PRIMARY_URL=${AIS_PRIMARY_URL} &&
        export AIS_CLD_PROVIDER=${AIS_CLD_PROVIDER} &&
        export AIS_CONF_FILE=/etc/ais/ais.json &&
        export STATSD_CONF_FILE="/etc/ais/statsd.conf" &&
        export COLLECTD_CONF_FILE="/etc/ais/collectd.conf" &&
        source /etc/ais/aisnode_config.sh &&
        aisnode -config=/etc/ais/ais.json -role=proxy -ntargets=${TARGET_CNT} -alsologtostderr=true;
  nodeSelector:
      nodename: ${PROXY_LABEL}
  volumes:
    - name: collectd-config
      configMap:
        name: collectd-config
    - name: statsd-config
      configMap:
        name: statsd-config
    - name: aws-credentials
      secret:
        secretName: aws-credentials
    - name: ais-log
      hostPath:
        path: /tmp
        type: Directory
