version: '3'
services:
#  Registry should not be started when deploying the cluster on minikube.
#  It conflicts with registry run by the minikube itself.
#
#  registry:
#    restart: always
#    image: registry:2
#    ports:
#      - 5000:5000
#    environment:
#      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
#      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
#    volumes:
#      - /certs:/certs
  ais:
    image: "localhost:5000/ais:v1"
    build:
      context: ./../../../
      dockerfile: ./deploy/dev/k8s/Dockerfile
      args:
        - TARGETS=${TARGET_CNT-1000}
        - AIS_CLD_PROVIDER=${AIS_CLD_PROVIDER-}
