#
# Enable the multiqueue schedulers in Ubuntu 18.04 - requires reboot for effect.
#
---
- hosts: '{{ playhosts | default("cpu-worker-node") }}'
  vars_files:
    - "vars.yml"

  gather_facts: false
  roles:
          - { role: ais_enable_multiqueue }
