#
# Apply our desired config to the k8s-cluster host group, which spans worker
# nodes, masters, and etcd nodes. Can override to a specific set of hosts
# by specifying targethosts on the cmdline.
#
# This config is intended to apply to *all* hosts; another playbook
# addresses specific needs for GPU hosts.
#
---
- hosts: '{{ play1hosts | default("k8s-cluster") }}'
  vars_files:
    - "vars.yml"

  gather_facts: true
  roles:
    - { role: ais_host_config_common }
    - pcm