apiVersion: apps/v1
kind: Deployment
metadata:
  name: aisclient
spec:
  selector:
    matchLabels:
      app: aisclient-app
  replicas: 1
  template:
    metadata:
      labels:
        app: aisclient-app
    spec:
      containers:
      - name: aisclient
        image: quay.io/nvidia/ais_client
        imagePullPolicy: Always
        ports:
          - containerPort: 30001
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
