---
- hosts: targets
  gather_facts: no
  tasks:
    - copy:
        src: "{{ playbook_dri }}/inventory/dfc.json"
        dest: /home/ubuntu/
        owner: ubuntu
        group: ubuntu
        mode: 0777
...

