---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  tasks:
    - copy:
        src: "{{ playbook_dir }}/setupnodes.sh"
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: 0777
    - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
      shell: /home/ubuntu/setupnodes.sh >> setupnodes.log
...

