---

  - name: add ais_node labels
    command: kubectl label nodes "{{ item }}" ais-node=yes --overwrite
    with_inventory_hostnames:
       -  proxy-node
       -  target-node
       -  neproxy-node
    environment:
        KUBECONFIG='/tmp/helm_deploy/kube.conf'
  - name: add node proxy labels
    command: kubectl label nodes "{{ item }}" ais-proxy-type=electable --overwrite
    with_inventory_hostnames:
       -  proxy-node
    environment:
        KUBECONFIG='/tmp/helm_deploy/kube.conf'
  - name: add target node labels
    command: kubectl label nodes "{{ item }}" ais-target-node=yes --overwrite
    with_inventory_hostnames:
        - target-node
    environment:
        KUBECONFIG=/tmp/helm_deploy/kube.conf
  - name: add NE proxy node labels
    command: kubectl label nodes "{{ item }}" ais-proxy-type=nonelectable --overwrite
    with_inventory_hostnames:
        - neproxy-node
  - name: add initial primary proxy node labels
    shell: |
       node_id=$(kubectl get nodes -l {{ ais_proxy_filter }} | grep node | grep Ready  | head -1| awk '{print $1}')   
       kubectl label nodes $node_id {{ initial_primary_proxy_label }} --overwrite
    environment:
        KUBECONFIG=/tmp/helm_deploy/kube.conf
