name: Docker Images

on:
  workflow_dispatch:
    inputs:
      build_admin_image:
        description: 'Build admin image (aistore/admin)'
        required: true
        type: boolean
        default: true

      build_aisnode_image:
        description: 'Build aisnode image (aistore/aisnode)'
        required: true
        type: boolean
        default: true

      build_cluster_minimal_image:
        description: 'Build cluster-minimal image (aistore/cluster-minimal)'
        required: true
        type: boolean
        default: true

      build_gitlab_ci_image:
        description: 'Build GitLab CI image (aistore/ci)'
        required: true
        type: boolean
        default: true

      build_aisnode_minikube_image:
        description: 'Build aisnode-minikube image (aistore/aisnode-minikube)'
        required: true
        type: boolean
        default: true

      image_tag:
        description: 'Tag of all the selected images'
        required: true
        default: 'latest'

env:
  ADMIN_IMAGE: 'aistore/admin'
  AISNODE_IMAGE: 'aistore/aisnode'
  CLUSTER_MINIMAL_IMAGE: 'aistore/cluster-minimal'
  CI_IMAGE: 'aistore/ci'
  AISNODE_MINIKUBE_IMAGE: 'aistore/aisnode-minikube'
  HDFS_CI_IMAGE: 'aistore/hdfs-ci'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: aisadmin image
      if: ${{ inputs.build_admin_image }}
      run: |
        pushd $GITHUB_WORKSPACE/deploy/prod/k8s/aisadmin_container
        IMAGE_REPO="${{ env.ADMIN_IMAGE }}" IMAGE_TAG="${{ inputs.image_tag }}" make -e all
        popd

    - name: aisnode image
      if: ${{ inputs.build_aisnode_image }}
      run: |
        pushd $GITHUB_WORKSPACE/deploy/prod/k8s/aisnode_container
        IMAGE_REPO="${{ env.AISNODE_IMAGE }}" IMAGE_TAG="${{ inputs.image_tag }}" make -e all
        popd

    - name: cluster-minimal image
      if: ${{ inputs.build_cluster_minimal_image }}
      run: |
        pushd $GITHUB_WORKSPACE/deploy/prod/docker/single
        IMAGE_REPO="${{ env.CLUSTER_MINIMAL_IMAGE }}" IMAGE_TAG="${{ inputs.image_tag }}" make -e all
        popd

    - name: ci image
      if: ${{ inputs.build_gitlab_ci_image }}
      run: |

        pushd $GITHUB_WORKSPACE/deploy/test/ci
        CI_IMAGE="${{ env.CI_IMAGE }}" HDFS_CI_IMAGE=${{ env.HDFS_CI_IMAGE }} IMAGE_TAG="${{ inputs.image_tag }}" make -e all
        popd

    - name: aisnode-minikube image
      if: ${{ inputs.build_aisnode_minikube_image }}
      run: |

        pushd $GITHUB_WORKSPACE/deploy/dev/k8s
        IMAGE_REPO="${{ env.AISNODE_MINIKUBE_IMAGE }}" IMAGE_TAG="${{ inputs.image_tag }}" make -e docker-all
        popd
